[package]
name = "autorel_chlg"
version = "0.1.5" # <- version
license = "Unlicense OR MIT"
authors = ["Jonathan Cornaz"]
edition = "2018"

[dependencies]
pest = "2.1"
pest_derive = "2.1.0"
git2 = "0.13.21"

[dev-dependencies]
rstest = "0.11.0"
