[package]
name = "autorel_chlg"
version = "0.1.4" # <- version
authors = ["Jonathan Cornaz"]
edition = "2018"

[dependencies]
pest = "2"
pest_derive = "2"
git2 = "0.13"

[dev-dependencies]
rstest = "0.10"
