[package]
name = "autorel_chlg"
version = "0.1.5" # <- version
license = "Unlicense OR MIT"
authors = ["Jonathan Cornaz"]
edition = "2018"

[dependencies]
pest = "2"
pest_derive = "2"
git2 = "0.13"

[dev-dependencies]
rstest = "0.10"
