[package]
name = "autorel"
version = "0.0.0"
authors = ["Jonathan Cornaz"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
clap = "3.0.0-beta.2"
git2 = "0.13"
semver = "0.11"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
clog = "0.9"
reqwest = { version = "0.11", features = ["blocking", "gzip", "brotli", "json"] }
regex = "1"
lazy_static = "1"

[dev-dependencies]
rstest = "0.9"
