[package]
name = "autorel"
version = "0.0.0"
authors = ["Jonathan Cornaz"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
clap = "3.0.0-beta.2"
git2 = "0.13"
semver = "0.11"
conventional-commits-parser = "0.1"
serde = "1"
serde_derive = "1"
toml = "0.5"

[dev-dependencies]
rstest = "0.9"
