name: Build

on:
  push:
    branches:
      - main
      - next-major

  pull_request:
    branches:
      - '*'

jobs:
  test:
    timeout-minutes: 20

    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable

    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Global cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-${{ matrix.os }}-${{ matrix.rust }}

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - name: Format check
        run: cargo fmt -- --check

      - name: Static analysis
        run: cargo clippy

      - name: Run tests
        run: cargo test --workspace --locked

  ignored-tests:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Global cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - name: Run ignored tests
        run: cargo test --workspace --locked -- --ignored
