name: Release

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight


jobs:
  release:
    timeout-minutes: 30

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Configure git
        run: |
          git config --global user.name "Jonathan Cornaz"
          git config --global user.email "jcornaz@users.noreply.github.com"

      - name: Global cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - name: Release
        run: cargo run --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
